apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1
  selector:
    matchLabels: { app: shop }
  template:
    metadata:
      labels: { app: shop }
    spec:
      containers:
        - name: shop
          image: ghcr.io/jwahn2018-rgb/5x5y-shop:latest
          ports:
            - containerPort: 80

