namespace: dev
resources:
  - ../../base

images:
  - name: ghcr.io/jwahn2018-rgb/5x5y-shop
    newName: ghcr.io/jwahn2018-rgb/5x5y-shop
<<<<<<< HEAD
  newTag: 99c018ec798037dc9430e299395feacb1da3e87b
=======
    newTag: 8af5efbf00e64712faeb457c18f5f59aa29d3119
>>>>>>> 1b0c850 (Fix dev kustomization indentation)
